### ISSUE TITLE
Wand doesnt work

### ISSUE THREAD

**Issue by amon28** [thebigsmileXD/MagicWE#37] opened 2017-04-20 08:57 UTC
I toggled the wand on but the wooden axe doesn't work it doesn't set positions

**Comment by thebigsmileXD** [comment] 2017-04-20 12:06
Duplicate of #35 and more
Learn to use the search tool. https://github.com/thebigsmileXD/MagicWE/issues?utf8=✓&q=is%3Aissue%20wand%20

**Closed** 2017-04-20 12:05 UTC
Labels: duplicate, invalid, Noob
